### ISSUE TITLE
More Catches because Essentials sucks.

### ISSUE THREAD

**Issue by fernferret** [fernferret/AllPay#8]
```
2011-08-15 15:21:36 [SEVERE] Error occurred while enabling Multiverse-Core v2.0-b218 (Is it up to date?): com/earth2me/essentials/api/UserDoesNotExistException
java.lang.NoClassDefFoundError: com/earth2me/essentials/api/UserDoesNotExistException
    at com.fernferret.allpay.AllPay.loadEssentialsEconomoy(AllPay.java:63)
    at com.fernferret.allpay.AllPay.loadEconPlugin(AllPay.java:44)
    at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:146)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:126)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:885)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:278)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:178)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:161)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:286)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:273)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:337)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)
Caused by: java.lang.ClassNotFoundException: com.earth2me.essentials.api.UserDoesNotExistException
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 13 more

```

**Comment by fernferret** [comment]
Should be fixed.
